#+TITLE: NodeJS
A C++ application, which embeds the V8 engine. The V8 engine is the Chrome javascript interpreter.
Node continuously checks the "event loop" on each tick, searching for new tasks. As soon soon as the
tasks are done, node exits.

Node is single-threaded, but tasks can be scheduled to be performed later, which avoids blocking IO.

1. Reads the file + dependencies
2. Executes synchronous tasks
3. Executes asynchronous tasks as soon as they are ready by looking at the event loop

* Install
The version on Ubuntu servers might be running on older version of node that you
might expect, be mindful of that!
~$ sudo apt install nodejs npm~
~$ sudo ln -s /usr/bin/nodejs /usr/bin/node~

** [[https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally][Resolving EACCES permissions errors when installing packages globally]]
The easiest way is to install node and npm via the [[https://docs.npmjs.com/downloading-and-installing-node-js-and-npm#using-a-node-version-manager-to-install-nodejs-and-npm][nvm (Node version manager)]], but there are othher
options too.

* Express
- [[https://www.amazon.com/dp/1074005309/?tag=nybblr08-20][Functional Design Patterns for Express.js]]
