#+TITLE: Pixel Art
#+AUTHOR: AnaRobynn
#+FILETAGS: :pixel_art:
#+STARTUP: hideblocks

* Introduction
  Controlling the color and position of each pixel.

** Where do I start?
*** Quick tips
   - *start small*: small canvas, small objects, not too hard
   - *limit colour palette*: make awesome stuff with a limited colour palette. The original
     [[https://www.designpieces.com/palette/game-boy-original-color-palette-hex-and-rgb/][GameBoy]] palette only include 14 colors! Whaaaat?
   - *filetypes*: prefer .png, avoid .jpg and be cautious with .gif

*** Software
    - *GIMP* is free, cross-platform and can do much more than Pixel Art.
    - *Pro Motion NG* is the industry standard for creating Pixel Art, but it's expensive
      (40 EUR + possible payment for future upgrades) and currently Windows is the only
      supported platform.
    - *Pyxel Edit* is the one I bought recently, because it's tailored towards Pixel Art,
      but it's cross-platform and only costs about 7 EUR.

*** Start!
    Two methods:
    - Outline first: Create the outline, then slowly refine and add colour
    - Sketch major blocks: Create the general gist of blocks and colour, refine for
      pixel-level polish

    Both of the methods work equally well and each have there purposes, so play around
    with both of them.

** Lines and curves
   *Lines* are composed of pixels and could be represented by a ratio y:x, as it's the ratio
   of change in y to the change in x. A perfect diagonal is presentented by 1:1, while
   other common lines are represented by 0:1, 1:2, 2:1 and 1:0.
   In the example of 2:1, it means that for each pixel moved on the x-axis, we draw 2
   pixel on the y-axis.

   *Curves* are lines which vary in a progressive manner, which avoid sharp angles. Draw out
   curves with a free hand, polish later.

   Example sequence: 5 4 3 2 2 1 1 1 2 3 3 3 2 1 1 2 2 1 2 1 2 1 1.

   Practice these techniques hard, because it's the base of Pixel Art!

** Color theory
   - Hue :: pure pigment - one without tint or shade - dominant wavelength
   - Value :: the amount of lightness or darkness of a colour (white vs black)
   - Saturation (also chroma) :: defines the brilliance and intensity of a colour (grey vs
        coloured)

** Dithering
   is an old technique invented when machines were too primitive to display a lot of
   colours. The human eye is imperfect and tends to to mix and blend the color of a pixel
   with the surrounding pixels.

   Patterns:
   - Checkerboard: 50/50 colour
