#+TITLE: Software Development
#+AUTHOR: AnaRobynn
#+FILETAGS: :software_development:
#+STARTUP: hideblocks

Related:

* Regaining agility
** Manifesto
   The people who develop software with agility favor the left side over the right.
   - *Individuals and Interactions* over Processes and Tools
   - *Working Software* over Comprehensive Documentation
   - *Customer Collaboration* over Contract Negotiation
   - *Responding to Change* over Following a Plan

** What does it mean, really?
   Facing two or more alternatives, that deliver the same value, take the one which makes
   future changes easier.
   1. Find out where you are
   2. Take a small step to your goal
   3. Adjust understanding, based on what you learned
   4. Repeat

* Scrum
** Dailies ([[https://martinfowler.com/articles/itsNotJustStandingUp.html][notjustastandup - Martin Fowler]])
   Everyone who wishes to known about and/or contributes to the status and progress of a
   project. The dialy is about coordination, aligning goals and sharing problems. Replace
   some or all meetings and reports with the daily standup.

   It shouldn't take more than 15min and  it's perfectly fine to time it. Meetings kill
   productivity.

** Story points
   are comparisons between rough relative sizes.

   If a story point becomes a clearly defined unit, someone is going to use it to
   compare the performance of other team. That's why you shouldn't standardize it (it's
   all relative)
