#+TITLE: NodeJS
#+AUTHOR: AnaRobynn
#+FILETAGS: :node:javascript:
#+STARTUP: hideblocks

* Background
** History
   Lots of drama, people didn't like it. People didn't care for JSON, until social media
   became big. Node and Mongo solved each other's problems. Google invited Ryan Dahl to
   speak at their conference.
   Node became very popular due to interesting npm packages like express.js, mongoose,
   angularjs, ... but that's also the pitfall of Node (or actually npm). People found node
   interesting not for the async, event driven nature, but for the massive amount of
   packages.

** What is it?
   A C++ application, which embeds the V8 engine. The V8 engine is the Chrome javascript
   interpreter. Node continuously checks the "event loop" on each tick, searching for new
   tasks. As soon soon as the tasks are done, node exits.

   Node is single-threaded, but tasks can be scheduled to be performed later, which avoids
   blocking IO.

   1. Reads the file + dependencies
   2. Executes synchronous tasks
   3. Executes asynchronous tasks as soon as they are ready by looking at the event loop

** Conventions
   - ENV variables
   - test/ directory
   - readme in root directory
   - code comments
     - @Param
     - @TODO
   - airbnb linting
   - error handling
     #+BEGIN_SRC javascript
       jedi(function(err, data){
         // check error
         // do some stuff
       })
     #+END_SRC

* RESTful API
  Allow users to login and enter certain URLs that needs to be monitored. Receiving alerts
  when the resources go down or back up => Uptime Monitor
