#+title: The C Programming Language
#+roam_tags: book reading
#+roam_key: https://www.goodreads.com/book/show/515601.The_C_Programming_Language
#+created: [2020-08-02 Sun 19:01]
#+modified: [2021-02-22 Mon 02:42]

* Metadata
- Author: [[roam:Brian W. Kernighan]]
- Reason: [[roam:Handmade Network]] considers it one of the best introductary material related to C
* Notes
** Introduction
*** Function declarations are allowed to be nested inside other functions, however function definitions are not allowed to be nested (unless via some C99 extensions).
*** C is quite a small language
- learning the language doesn't take much time.
- lacks a lot of common features which is taken for granted in Javascript => comparing two characters with each other.
  => slightly solved by including a standard library with the C implementations.
*** C is statically typed via the compiler, but is weakly typed, because the languages assumes the programmer knows what they are doing. For example, you can cast any pointer type, to any other pointer type.
** Chapter 1: A Tutorial Introduction
*** Dividing integers results in a truncation of the value. Let's say you woud like to calcuate 5/9, that would evaluate to 0 and the fractional part is thrown away. That's why it's beneficial to calculate multiplication, before doing the division (while in math the order is equal).
:PROPERTIES:
:ID:       7230a04a-18ba-4be2-98b9-cdd9a3fcb31d
:END:
*** Interesting fact is that ~printf~ is NOT part of the C language itself, but it's part of the ANSI standard.
*** A symbolic names AKA ~#define~ is literally a search and replace.
*** An assignment is an expression and has a value at the same time.
*** ~EOF~'s value is -1, which is why ~getchar()~ needs to be represented as an ~int~ rather than a ~char~.
*** ~int~ and ~long~ are usually different in size, but in certain machines they are the same.
*** Storing a /character constant/ like ~'A'~ is another way to write a small integer (because a char is only 1 byte, while an actual int is 4 bytes), because the numerical value gets stored whatever the representation is of the particular character set.
* Highlights
